version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      LOG_LEVEL: DEBUG
      DRY_RUN: "true"
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: /api
        NEXT_BACKEND_URL: http://backend:8000
        NEXT_PUBLIC_PICKUP_NAME: Preetizen Lifestyle
        NEXT_PUBLIC_PICKUP_CITY: Kolkata
        NEXT_PUBLIC_PICKUP_PIN: "700107"
        NEXT_PUBLIC_PICKUP_COUNTRY: India
        NEXT_PUBLIC_HSN_CODE: "851770"
        NEXT_PUBLIC_CONSIGNEE_GST_AMOUNT: "150.00"
        NEXT_PUBLIC_INTEGRATED_GST_AMOUNT: "275.50"
        NEXT_PUBLIC_CONSIGNEE_GST_TIN: 27ABCDE1234F1Z5
        NEXT_PUBLIC_GST_CESS_AMOUNT: "35.25"
    environment:
      NEXT_PUBLIC_API_BASE_URL: /api
      NEXT_BACKEND_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"
